git:
  url: "http://gitlab.domain/project.git"
  repoName: "project-name"
  branch: "master"
  commitID: "commit123"
web:
  deployName: name-branch-serv
pipeline:
  sequence: 0
webinspect:
  runnerVersion: 1.1.0
