harbor:
  host: "harbor.domain"
  cache: dockerhub
git:
  url: "http://gitlab.domain/project.git"
  repoName: "project-name"
  branch: "master"
  commitID: "commit123"
web:
  deployName: name-branch-serv-dpy
  port: 80
pipeline:
  sequence: 0
newman:
  runnerVersion: 2.0.1
