{{ if and (eq .Values.db.enabled true) (eq .Values.db.gui true) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gui
  labels:
    app: {{ .Release.Name }}-gui
  annotations:
    {{- include "iiidevops.annotations" . | nindent 4 }}
    iiidevops.org/type: db-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-gui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-gui
      annotations:
        {{- include "iiidevops.annotations" . | nindent 8 }}
        iiidevops.org/type: db-gui
    spec:
      #backoffLimit: 2
      containers:
        - name: {{ .Values.db.type }}-gui
          imagePullPolicy: IfNotPresent
        # 按照使用者要求的資料庫去配置對應的網頁管理鏡像，基本上除了mongodb獨特，其他都可以用adminer
        {{- if eq .Values.db.type "mariadb" }}
          image: "bitnami/phpmyadmin"
        {{- else if eq .Values.db.type "mongodb" }}
          image: "mongo-express"
        {{- else }}
          image: "adminer"
        {{- end }}
          ports:
            - name: dbgui
            {{- if eq .Values.db.type "mysql" }}
              containerPort: 8080
            {{- else if eq .Values.db.type "mariadb" }}
              containerPort: 8080
            {{- else if eq .Values.db.type "postgresql" }}
              containerPort: 8080
            {{- else if eq .Values.db.type "mongodb" }}
              containerPort: 8081
            {{- end }}
              protocol: TCP
          env:
        # 先保留給予後續鏡像環境設定時候使用
        {{- if eq .Values.db.type "mysql" }}
          - name: ADMINER_DEFAULT_SERVER
            value: "{{ .Release.Name }}-svc"
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.db.rootpassword }}
        {{- else if eq .Values.db.type "mariadb" }}
          - name: DATABASE_HOST
            value: "{{ .Release.Name }}-svc"
          - name: DATABASE_ALLOW_NO_PASSWORD
            value: "no"
        {{- else if eq .Values.db.type "postgresql" }}
          - name: ADMINER_DEFAULT_SERVER
            value: "{{ .Release.Name }}-svc"
          - name: POSTGRESQL_USERNAME
            value: root
          - name: POSTGRESQL_PASSWORD
            value: {{ .Values.db.rootpassword }}
        {{- else if eq .Values.db.type "mongodb" }}
          - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
            value: 'false'
          - name: ME_CONFIG_MONGODB_AUTH_DATABASE
            value: "{{ .Release.Name }}-svc"
          - name: ME_CONFIG_MONGODB_AUTH_USERNAME
            value: {{ .Values.db.username }}
          - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
            value: {{ .Values.db.password }}
        {{- end }}
{{- end }}
