apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dpy
  labels:
    app: {{ .Release.Name }}
  annotations:
    {{- include "iiidevops.annotations" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        {{- include "iiidevops.annotations" . | nindent 8 }}
    spec:
      #backoffLimit: 2
      imagePullSecrets:
        {{- .Values.imagePullSecrets | toYaml | nindent 8 }}
      containers:
        - name: web-server-{{ include "numericSafe" .Values.git.commitID }}
          image: {{ .Values.harbor.host }}/{{ .Values.web.imageTag }}
          imagePullPolicy: Always
          env:
            - name: repo_name
              value: {{ .Values.git.repoName }}
            - name: git_branch
              value: {{ include "numericSafe" .Values.git.branch | quote }}
            - name: git_commit_id
              value: {{ include "numericSafe" .Values.git.commitID | quote }}
            - name: db_host
              value: {{ .Values.db.releaseName }}-svc
            - name: db_name
              value: {{ .Values.db.name }}
            - name: db_username
              value: {{ .Values.db.username }}
            - name: db_password
              value: {{ .Values.db.password }}
          ports:
            - containerPort: {{ .Values.web.port }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: "{{ .Values.git.repoName }}-{{ .Values.git.branch }}-env"
